performance:
  min-threads: 1
  max-threads: 10
  max-rtp-lookup: 1000
defaults:
  region-radius: 5
  highlight-radius: 20
  rtp-radius: 3
  starting-balance: 350
objectives-data:
  balance:
    item: STICK
  war:
    item: WOODEN_AXE